cargo-features = ["edition2024"]

[workspace]
resolver = "3"
members = [
    "susos",
    "microloader",
]

[profile.dev]
panic = "abort"

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
panic = "abort"
